import flet as ft
import oracledb
import os
import bcrypt
import requests
import datetime
from dotenv import load_dotenv

# Carga de variables del archivo .env
load_dotenv()

class BaseDatos:
    def __init__(self):
        self.usuario = os.getenv("ORACLE_USER")
        self.clave = os.getenv("ORACLE_PASSWORD")
        self.dsn = os.getenv("ORACLE_DSN")

    def obtener_conexion(self):
        try:
            return oracledb.connect(user=self.usuario, password=self.clave, dsn=self.dsn)
        except Exception:
            return None

    def crear_tablas(self):
        self.ejecutar("""
            CREATE TABLE USERS (
                id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                username VARCHAR2(50) NOT NULL UNIQUE,
                password_hash VARCHAR2(100) NOT NULL
            )
        """)
        self.ejecutar("""
            CREATE TABLE INDICATOR_LOG (
                log_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                indicator_name VARCHAR2(50),
                indicator_value NUMBER,
                value_date DATE,
                query_date DATE,
                username_query VARCHAR2(50),
                source_site VARCHAR2(100)
            )
        """)

    def ejecutar(self, sql, parametros=None, es_select=False):
        try:
            with self.obtener_conexion() as conn:
                if not conn: return None
                with conn.cursor() as cursor:
                    cursor.execute(sql, parametros or {})
                    if es_select:
                        return cursor.fetchall()
                    conn.commit()
                    return True
        except Exception as e:
            if "ORA-00955" in str(e): return True
            return None

class ServicioAPI:
    def __init__(self):
        self.url_base = "https://mindicador.cl/api"

    def obtener_dato_api(self, db, usuario_sesion, tipo_indicador, fecha_usuario):
        # Lógica para manejar consulta actual o por fecha
        if not fecha_usuario or fecha_usuario.strip() == "":
            url_completa = f"{self.url_base}/{tipo_indicador}"
        elif len(fecha_usuario.strip()) == 8 and fecha_usuario.isdigit():
            f = fecha_usuario.strip()
            fecha_final = f"{f[0:2]}-{f[2:4]}-{f[4:8]}"
            url_completa = f"{self.url_base}/{tipo_indicador}/{fecha_final}"
        else:
            url_completa = f"{self.url_base}/{tipo_indicador}/{fecha_usuario}"
        
        try:
            peticion = requests.get(url_completa, timeout=10)
            datos = peticion.json()
            
            if "serie" in datos and len(datos["serie"]) > 0:
                valor_encontrado = datos["serie"][0]["valor"]
                nombre_indicador = datos["nombre"]
                fecha_valor_str = datos["serie"][0]["fecha"][:10]
                
                sql_audit = """INSERT INTO INDICATOR_LOG 
                               (indicator_name, indicator_value, value_date, query_date, username_query, source_site)
                               VALUES (:n, :v, :vd, :qd, :u, :s)"""
                params = {
                    "n": nombre_indicador,
                    "v": valor_encontrado,
                    "vd": datetime.datetime.strptime(fecha_valor_str, "%Y-%m-%d"),
                    "qd": datetime.datetime.now(),
                    "u": usuario_sesion,
                    "s": "mindicador.cl"
                }
                db.ejecutar(sql_audit, params)
                return {"valor": valor_encontrado, "unidad": datos["unidad_medida"], "fecha": fecha_valor_str}
        except Exception:
            return None
        return None

class InterfazApp:
    def __init__(self, page: ft.Page):
        self.page = page
        self.page.title = "Ecotech Solutions - Final"
        self.page.window_width = 450
        self.page.window_height = 650
        self.db = BaseDatos()
        self.api = ServicioAPI()
        self.usuario_conectado = None
        
        self.db.crear_tablas()
        self.mostrar_login()

    def mostrar_login(self, e=None):
        self.page.controls.clear()
        # Uso de strings para los iconos para evitar el error de AtributeError
        user_tf = ft.TextField(label="Usuario", prefix_icon="person")
        pass_tf = ft.TextField(label="Password", password=True, prefix_icon="lock")
        error_lbl = ft.Text(color="red")

        def login_click(e):
            datos = self.db.ejecutar("SELECT password_hash FROM USERS WHERE username = :u", {"u": user_tf.value}, True)
            if datos and bcrypt.checkpw(pass_tf.value.encode('utf-8'), datos[0][0].encode('utf-8')):
                self.usuario_conectado = user_tf.value
                self.mostrar_menu()
            else:
                error_lbl.value = "Usuario o clave incorrecta"
                self.page.update()

        self.page.add(
            ft.Text("Acceso al Sistema", size=25, weight="bold"),
            user_tf, pass_tf,
            ft.ElevatedButton("Entrar", on_click=login_click, width=200, bgcolor="blue", color="white"),
            ft.TextButton("¿No tienes cuenta? Registrate", on_click=self.mostrar_registro),
            ft.Divider(),
            ft.ElevatedButton("Salir de la App", on_click=lambda _: self.page.window_close(), color="red"),
            error_lbl
        )
        self.page.update()

    def mostrar_registro(self, e=None):
        self.page.controls.clear()
        u = ft.TextField(label="Nombre de Usuario")
        p = ft.TextField(label="Contrasena", password=True)

        def registrar_click(e):
            if not u.value or not p.value: return
            hash_pw = bcrypt.hashpw(p.value.encode('utf-8'), bcrypt.gensalt(12)).decode('utf-8')
            if self.db.ejecutar("INSERT INTO USERS (username, password_hash) VALUES (:u, :p)", {"u": u.value, "p": hash_pw}):
                self.mostrar_login()

        self.page.add(
            ft.Text("Registro de Usuario", size=25),
            u, p,
            ft.ElevatedButton("Crear Cuenta", on_click=registrar_click),
            ft.TextButton("Volver", on_click=self.mostrar_login)
        )
        self.page.update()

    def mostrar_menu(self):
        self.page.controls.clear()
        self.page.add(
            ft.Text(f"Sesion activa: {self.usuario_conectado}", italic=True),
            ft.Text("Menu Principal", size=30, weight="bold"),
            ft.Divider(),
            ft.ListTile(leading=ft.Icon("search"), title=ft.Text("Consultar API"), on_click=self.mostrar_consulta),
            ft.ListTile(leading=ft.Icon("history"), title=ft.Text("Ver Auditoria"), on_click=self.mostrar_historial),
            ft.Divider(),
            ft.TextButton("Cerrar Sesion", on_click=self.mostrar_login),
            ft.ElevatedButton("Salir de Aplicacion", on_click=lambda _: self.page.window_close(), color="red")
        )
        self.page.update()

    def mostrar_consulta(self, e=None):
        self.page.controls.clear()
        drop = ft.Dropdown(label="Indicador", options=[
            ft.dropdown.Option("uf", "UF"),
            ft.dropdown.Option("ivp", "IVP"),  # <--- Agregado IVP
            ft.dropdown.Option("dolar", "Dolar"),
            ft.dropdown.Option("euro", "Euro"),
            ft.dropdown.Option("utm", "UTM"),
            ft.dropdown.Option("ipc", "IPC")
        ])
        fecha_tf = ft.TextField(label="Fecha", hint_text="Vacio = Hoy | O usa DDMMYYYY")
        msg = ft.Text(size=18, weight="bold")

        def consultar_click(e):
            if not drop.value: return
            res = self.api.obtener_dato_api(self.db, self.usuario_conectado, drop.value, fecha_tf.value)
            if res:
                msg.value = f"Fecha: {res['fecha']}\nValor: {res['valor']} {res['unidad']}"
                msg.color = "blue"
            else:
                msg.value = "Error: Sin datos"
                msg.color = "red"
            self.page.update()

        self.page.add(
            ft.Text("Consulta de Indicadores", size=20),
            drop, fecha_tf,
            ft.ElevatedButton("Consultar y Registrar", on_click=consultar_click, width=250),
            msg,
            ft.TextButton("Volver al Menu", on_click=lambda _: self.mostrar_menu())
        )
        self.page.update()

    def mostrar_historial(self, e=None):
        self.page.controls.clear()
        logs = self.db.ejecutar("""
            SELECT indicator_name, indicator_value, value_date, query_date 
            FROM INDICATOR_LOG WHERE username_query = :u ORDER BY query_date DESC
        """, {"u": self.usuario_conectado}, True)
        
        lista = ft.ListView(expand=True, spacing=10)
        if logs:
            for l in logs:
                # l[2] es la fecha del valor, l[3] es la fecha de consulta (auditoría)
                f_val = l[2].strftime('%d-%m-%Y') if l[2] else "N/A"
                f_aud = l[3].strftime('%H:%M') if l[3] else "N/A"
                lista.controls.append(
                    ft.Card(content=ft.Container(padding=10, content=ft.Column([
                        ft.Text(f"Indicador: {l[0]}", weight="bold"),
                        ft.Text(f"Valor: {l[1]} | Ref: {f_val}"),
                        ft.Text(f"Auditado: {f_aud}", size=10)
                    ])))
                )
        self.page.add(
            ft.Text("Auditoria", size=20),
            lista,
            ft.ElevatedButton("Volver", on_click=lambda _: self.mostrar_menu())
        )
        self.page.update()

def main(page: ft.Page):
    InterfazApp(page)

if __name__ == "__main__":
    ft.app(target=main)