import flet as ft
import oracledb
import os
import bcrypt
import requests
import datetime
from dotenv import load_dotenv

load_dotenv()

# --- CLASE BASE DE DATOS ---
class BaseDatos:
    def __init__(self):
        self.usuario = os.getenv("ORACLE_USER", "")
        self.clave = os.getenv("ORACLE_PASSWORD", "")
        self.dsn = os.getenv("ORACLE_DSN", "")

    def obtener_conexion(self):
        try:
            if not self.usuario or not self.clave: return None
            return oracledb.connect(user=self.usuario, password=self.clave, dsn=self.dsn)
        except: return None

    def ejecutar(self, sql, parametros=None, es_select=False):
        conn = self.obtener_conexion()
        if not conn: return None
        try:
            with conn:
                with conn.cursor() as cursor:
                    cursor.execute(sql, parametros or {})
                    if es_select: return cursor.fetchall()
                    conn.commit()
                    return True
        except Exception as e:
            if "ORA-00955" not in str(e): print(f"Error SQL: {e}")
            return None

    def inicializar_tablas(self):
        self.ejecutar("CREATE TABLE USERS (id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, username VARCHAR2(50) NOT NULL UNIQUE, password_hash VARCHAR2(100) NOT NULL)")
        self.ejecutar("CREATE TABLE INDICATOR_LOG (log_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, indicator_name VARCHAR2(50), indicator_value NUMBER, value_date DATE, query_date DATE, username_query VARCHAR2(50), source_site VARCHAR2(100))")

# --- SERVICIO API ---
class ServicioAPI:
    def __init__(self):
        self.url_base = "https://mindicador.cl/api"

    def consultar(self, db, usuario, indicador, fecha_str):
        url = f"{self.url_base}/{indicador}"
        if fecha_str and len(fecha_str.strip()) == 8:
            f = fecha_str.strip()
            url = f"{url}/{f[0:2]}-{f[2:4]}-{f[4:8]}"
        try:
            resp = requests.get(url, timeout=7)
            datos = resp.json()
            if "serie" in datos and len(datos["serie"]) > 0:
                item = datos["serie"][0]
                val, f_val_str = item["valor"], item["fecha"][:10]
                db.ejecutar("INSERT INTO INDICATOR_LOG (indicator_name, indicator_value, value_date, query_date, username_query, source_site) VALUES (:n, :v, :vd, :qd, :u, :s)",
                           {"n": datos.get("nombre"), "v": val, "vd": datetime.datetime.strptime(f_val_str, "%Y-%m-%d"), "qd": datetime.datetime.now(), "u": usuario, "s": "mindicador.cl"})
                return {"valor": val, "unidad": datos.get("unidad_medida"), "fecha": f_val_str}
        except: return None

# --- INTERFAZ ESCRITORIO ---
class EcotechApp:
    def __init__(self, page: ft.Page):
        self.page = page
        self.page.title = "Ecotech Finanzas - Desktop"
        # Configuración para Escritorio (Horizontal)
        self.page.window_width = 1000
        self.page.window_height = 700
        self.page.theme_mode = ft.ThemeMode.LIGHT
        
        # Evitar errores de atributo usando alineaciones de nivel de página simples
        self.page.vertical_alignment = ft.MainAxisAlignment.CENTER
        self.page.horizontal_alignment = ft.CrossAxisAlignment.CENTER
        
        self.db = BaseDatos()
        self.api = ServicioAPI()
        self.usuario_actual = None
        
        self.db.inicializar_tablas()
        self.mostrar_login()

    def mostrar_login(self):
        self.page.clean()
        
        user_tf = ft.TextField(label="Usuario", width=300, prefix_icon="person")
        pass_tf = ft.TextField(label="Contraseña", password=True, width=300, prefix_icon="lock")

        def login_click(e):
            res = self.db.ejecutar("SELECT password_hash FROM USERS WHERE username = :u", {"u": user_tf.value}, True)
            if res and bcrypt.checkpw(pass_tf.value.encode('utf-8'), res[0][0].encode('utf-8')):
                self.usuario_actual = user_tf.value
                self.mostrar_dashboard()
            else:
                self.page.snack_bar = ft.SnackBar(ft.Text("Credenciales inválidas"))
                self.page.snack_bar.open = True
                self.page.update()

        # Contenedor centrado para el Login
        login_card = ft.Container(
            content=ft.Column([
                ft.Icon("eco", size=70, color="teal"),
                ft.Text("ECOTECH SOLUTIONS", size=24, weight="bold", color="teal"),
                user_tf, pass_tf,
                ft.FilledButton("INICIAR SESIÓN", on_click=login_click, width=300),
                ft.TextButton("Registrar cuenta nueva", on_click=lambda _: self.mostrar_registro())
            ], horizontal_alignment="center", spacing=20),
            padding=40, bgcolor="white", border_radius=15, 
            shadow=ft.BoxShadow(blur_radius=20, color="#1A000000")
        )
        
        self.page.add(login_card)
        self.page.update()

    def mostrar_registro(self):
        self.page.clean()
        u = ft.TextField(label="Nuevo Usuario", width=300)
        p = ft.TextField(label="Contraseña", password=True, width=300)

        def reg_click(e):
            h = bcrypt.hashpw(p.value.encode('utf-8'), bcrypt.gensalt()).decode('utf-8')
            if self.db.ejecutar("INSERT INTO USERS (username, password_hash) VALUES (:u, :p)", {"u": u.value, "p": h}):
                self.mostrar_login()

        self.page.add(
            ft.Column([
                ft.Text("Crea tu cuenta", size=20, weight="bold"),
                u, p,
                ft.FilledButton("REGISTRAR", on_click=reg_click, width=300),
                ft.TextButton("Volver", on_click=lambda _: self.mostrar_login())
            ], horizontal_alignment="center")
        )
        self.page.update()

    def mostrar_dashboard(self):
        self.page.clean()
        self.page.horizontal_alignment = ft.CrossAxisAlignment.STRETCH
        self.page.vertical_alignment = ft.MainAxisAlignment.START

        # Sidebar Lateral
        sidebar = ft.Container(
            content=ft.Column([
                ft.Text("MENÚ", weight="bold", color="white70"),
                ft.Divider(color="white24"),
                ft.ListTile(leading=ft.Icon("search", color="white"), title=ft.Text("Consultar", color="white"), on_click=lambda _: self.mostrar_contenido_consulta()),
                ft.ListTile(leading=ft.Icon("history", color="white"), title=ft.Text("Historial", color="white"), on_click=lambda _: self.mostrar_contenido_historial()),
                ft.VerticalDivider(expand=True),
                ft.ListTile(leading=ft.Icon("logout", color="red"), title=ft.Text("Cerrar Sesión", color="red"), on_click=lambda _: self.mostrar_login()),
            ], spacing=10),
            padding=20, bgcolor="#2C3E50", width=250, border_radius=ft.border_radius.only(top_right=20, bottom_right=20)
        )

        self.contenido_principal = ft.Container(
            content=ft.Text("Selecciona una opción del menú", size=18, color="grey"),
            expand=True, padding=40
        )

        # Layout principal de escritorio
        self.page.add(
            ft.Row([
                sidebar,
                self.contenido_principal
            ], expand=True)
        )
        self.page.update()

    def mostrar_contenido_consulta(self):
        drop = ft.Dropdown(label="Seleccione Indicador", width=400, options=[
            ft.dropdown.Option("uf", "UF"), ft.dropdown.Option("dolar", "Dólar"),
            ft.dropdown.Option("euro", "Euro"), ft.dropdown.Option("utm", "UTM")
        ])
        res_txt = ft.Text(size=24, weight="bold", color="teal")

        def buscar(e):
            res = self.api.consultar(self.db, self.usuario_actual, drop.value, "")
            if res: res_txt.value = f"Valor Actual: ${res['valor']} {res['unidad']}"
            else: res_txt.value = "No se encontraron datos."
            self.page.update()

        self.contenido_principal.content = ft.Column([
            ft.Text("Consultar Indicadores en Tiempo Real", size=24, weight="bold"),
            ft.Divider(),
            drop,
            ft.FilledButton("CONSULTAR AHORA", on_click=buscar, width=200),
            ft.Container(content=res_txt, padding=30, bgcolor="#F4F6F7", border_radius=10)
        ], spacing=20)
        self.page.update()

    def mostrar_contenido_historial(self):
        logs = self.db.ejecutar("SELECT indicator_name, indicator_value, query_date FROM INDICATOR_LOG WHERE username_query = :u ORDER BY query_date DESC", {"u": self.usuario_actual}, True)
        
        # Tabla de datos para escritorio
        tabla = ft.DataTable(
            columns=[
                ft.DataColumn(ft.Text("Indicador")),
                ft.DataColumn(ft.Text("Valor")),
                ft.DataColumn(ft.Text("Fecha Consulta")),
            ],
            rows=[]
        )

        if logs:
            for l in logs:
                tabla.rows.append(ft.DataRow(cells=[
                    ft.DataCell(ft.Text(l[0])),
                    ft.DataCell(ft.Text(f"${l[1]}")),
                    ft.DataCell(ft.Text(l[2].strftime("%d/%m/%Y %H:%M"))),
                ]))

        self.contenido_principal.content = ft.Column([
            ft.Text("Historial de Auditoría", size=24, weight="bold"),
            ft.Divider(),
            ft.Column([tabla], scroll=ft.ScrollMode.AUTO, expand=True)
        ], spacing=20)
        self.page.update()

def main(page: ft.Page):
    EcotechApp(page)

if __name__ == "__main__":
    ft.app(target=main)