import flet as ft
import oracledb
import os
import bcrypt
import requests
import datetime
from dotenv import load_dotenv

# Carga de variables del archivo .env
load_dotenv()

# --- CLASE BASE DE DATOS ---
class BaseDatos:
    def __init__(self):
        self.usuario = os.getenv("ORACLE_USER")
        self.clave = os.getenv("ORACLE_PASSWORD")
        self.dsn = os.getenv("ORACLE_DSN")

    def obtener_conexion(self):
        try:
            return oracledb.connect(user=self.usuario, password=self.clave, dsn=self.dsn)
        except Exception as e:
            print(f"Error de conexión: {e}")
            return None

    def crear_tablas(self):
        # Intentamos crear las tablas. Si existen, ignoramos el error.
        self.ejecutar("""
            CREATE TABLE USERS (
                id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                username VARCHAR2(50) NOT NULL UNIQUE,
                password_hash VARCHAR2(100) NOT NULL
            )
        """)
        self.ejecutar("""
            CREATE TABLE INDICATOR_LOG (
                log_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                indicator_name VARCHAR2(50),
                indicator_value NUMBER,
                value_date DATE,
                query_date DATE,
                username_query VARCHAR2(50),
                source_site VARCHAR2(100)
            )
        """)

    def ejecutar(self, sql, parametros=None, es_select=False):
        try:
            with self.obtener_conexion() as conn:
                if not conn: return None
                with conn.cursor() as cursor:
                    cursor.execute(sql, parametros or {})
                    if es_select:
                        return cursor.fetchall()
                    conn.commit()
                    return True
        except Exception as e:
            # ORA-00955: nombre ya está siendo utilizado por un objeto existente
            if "ORA-00955" not in str(e):
                print(f"Error SQL: {e}")
            return None

# --- SERVICIO API (CORREGIDO) ---
class ServicioAPI:
    def __init__(self):
        self.url_base = "https://mindicador.cl/api"

    def obtener_dato_api(self, db, usuario_sesion, tipo_indicador, fecha_usuario):
        url_completa = f"{self.url_base}/{tipo_indicador}"
        fecha_para_bd = None
        
        # Lógica de fecha corregida
        if fecha_usuario and len(fecha_usuario.strip()) == 8 and fecha_usuario.isdigit():
            # Si el usuario pide una fecha específica (DDMMYYYY)
            f = fecha_usuario.strip()
            fecha_formato_api = f"{f[0:2]}-{f[2:4]}-{f[4:8]}" # dd-mm-yyyy
            url_completa = f"{url_completa}/{fecha_formato_api}"
            fecha_para_bd = datetime.datetime.strptime(fecha_formato_api, "%d-%m-%Y")
        else:
            # Si está vacío, NO agregamos fecha a la URL.
            # La API devolverá el último valor disponible (útil fines de semana).
            fecha_para_bd = datetime.datetime.now()

        try:
            peticion = requests.get(url_completa, timeout=10)
            if peticion.status_code != 200:
                return None
                
            datos = peticion.json()
            
            # La API devuelve 'serie' como una lista. 
            # Si consultamos sin fecha, la lista trae los últimos 30 días, el index 0 es el más actual.
            if "serie" in datos and len(datos["serie"]) > 0:
                item = datos["serie"][0]
                valor_encontrado = item["valor"]
                # La fecha real del valor (puede ser distinta a hoy si es fin de semana)
                fecha_valor_str = item["fecha"][:10] 
                fecha_valor_dt = datetime.datetime.strptime(fecha_valor_str, "%Y-%m-%d")
                
                nombre_indicador = datos.get("nombre", tipo_indicador)
                
                # Insertar en Oracle
                sql_audit = """INSERT INTO INDICATOR_LOG 
                               (indicator_name, indicator_value, value_date, query_date, username_query, source_site)
                               VALUES (:n, :v, :vd, :qd, :u, :s)"""
                params = {
                    "n": nombre_indicador,
                    "v": valor_encontrado,
                    "vd": fecha_valor_dt,
                    "qd": datetime.datetime.now(),
                    "u": usuario_sesion,
                    "s": "mindicador.cl"
                }
                db.ejecutar(sql_audit, params)
                
                return {
                    "valor": valor_encontrado, 
                    "unidad": datos.get("unidad_medida", "Pesos"), 
                    "fecha": fecha_valor_str
                }
        except Exception as e:
            print(f"Error API: {e}")
            return None
        return None

# --- INTERFAZ GRÁFICA (MEJORADA) ---
class InterfazApp:
    def __init__(self, page: ft.Page):
        self.page = page
        self.page.title = "Ecotech Solutions - Finanzas"
        # Corrección de propiedades deprecadas
        self.page.window.width = 400
        self.page.window.height = 700
        self.page.theme_mode = ft.ThemeMode.LIGHT
        self.page.vertical_alignment = ft.MainAxisAlignment.CENTER
        self.page.horizontal_alignment = ft.CrossAxisAlignment.CENTER
        
        self.db = BaseDatos()
        self.api = ServicioAPI()
        self.usuario_conectado = None
        
        # Inicializar DB y mostrar Login
        self.db.crear_tablas()
        self.mostrar_login()

    def mostrar_mensaje(self, texto, color="red"):
        snack = ft.SnackBar(ft.Text(texto), bgcolor=color)
        self.page.open(snack) # Sintaxis moderna para Flet

    def limpiar_pantalla(self):
        self.page.clean()

    def mostrar_login(self, e=None):
        self.limpiar_pantalla()
        
        user_tf = ft.TextField(label="Usuario", prefix_icon=ft.icons.PERSON, width=300)
        pass_tf = ft.TextField(label="Contraseña", password=True, can_reveal_password=True, prefix_icon=ft.icons.LOCK, width=300)

        def login_click(e):
            if not user_tf.value or not pass_tf.value:
                self.mostrar_mensaje("Complete todos los campos")
                return

            datos = self.db.ejecutar("SELECT password_hash FROM USERS WHERE username = :u", {"u": user_tf.value}, True)
            
            if datos and bcrypt.checkpw(pass_tf.value.encode('utf-8'), datos[0][0].encode('utf-8')):
                self.usuario_conectado = user_tf.value
                self.mostrar_mensaje("Bienvenido", "green")
                self.mostrar_menu()
            else:
                self.mostrar_mensaje("Credenciales inválidas")

        self.page.add(
            ft.Container(
                content=ft.Column([
                    ft.Icon(ft.icons.ECO, size=60, color="green"),
                    ft.Text("Ecotech Finanzas", size=24, weight="bold"),
                    ft.Divider(height=20, color="transparent"),
                    user_tf, 
                    pass_tf,
                    ft.ElevatedButton("Iniciar Sesión", on_click=login_click, width=300, bgcolor="blue", color="white"),
                    ft.TextButton("Crear una cuenta nueva", on_click=self.mostrar_registro)
                ], horizontal_alignment=ft.CrossAxisAlignment.CENTER),
                padding=20
            )
        )

    def mostrar_registro(self, e=None):
        self.limpiar_pantalla()
        u = ft.TextField(label="Nuevo Usuario", width=300)
        p = ft.TextField(label="Nueva Contraseña", password=True, width=300)

        def registrar_click(e):
            if not u.value or not p.value: 
                self.mostrar_mensaje("Campos vacíos")
                return
            
            try:
                hash_pw = bcrypt.hashpw(p.value.encode('utf-8'), bcrypt.gensalt(12)).decode('utf-8')
                res = self.db.ejecutar("INSERT INTO USERS (username, password_hash) VALUES (:u, :p)", {"u": u.value, "p": hash_pw})
                if res:
                    self.mostrar_mensaje("Usuario creado. Inicie sesión", "green")
                    self.mostrar_login()
                else:
                    self.mostrar_mensaje("Error: El usuario ya existe o BD caída")
            except Exception as ex:
                self.mostrar_mensaje(f"Error crítico: {str(ex)}")

        self.page.add(
            ft.Column([
                ft.Text("Registro", size=30, weight="bold"),
                u, p,
                ft.ElevatedButton("Registrarme", on_click=registrar_click, width=300, bgcolor="green", color="white"),
                ft.TextButton("Volver al Login", on_click=self.mostrar_login)
            ], horizontal_alignment=ft.CrossAxisAlignment.CENTER)
        )

    def mostrar_menu(self):
        self.limpiar_pantalla()
        self.page.add(
            ft.Column([
                ft.Row([ft.Icon(ft.icons.PERSON), ft.Text(f"Hola, {self.usuario_conectado}", weight="bold")], alignment=ft.MainAxisAlignment.CENTER),
                ft.Divider(),
                ft.Container(
                    content=ft.Column([
                        ft.ElevatedButton("Consultar Indicadores", icon=ft.icons.SEARCH, width=280, on_click=self.mostrar_consulta, height=50),
                        ft.ElevatedButton("Ver Historial", icon=ft.icons.HISTORY, width=280, on_click=self.mostrar_historial, height=50),
                    ]),
                    padding=20
                ),
                ft.Divider(),
                ft.TextButton("Cerrar Sesión", icon=ft.icons.EXIT_TO_APP, on_click=self.mostrar_login, icon_color="red", style=ft.ButtonStyle(color="red"))
            ], horizontal_alignment=ft.CrossAxisAlignment.CENTER)
        )

    def mostrar_consulta(self, e=None):
        self.limpiar_pantalla()
        
        # Opciones válidas para la API
        drop = ft.Dropdown(label="Seleccione Indicador", width=300, options=[
            ft.dropdown.Option("uf"),
            ft.dropdown.Option("dolar"),
            ft.dropdown.Option("euro"),
            ft.dropdown.Option("utm"),
            ft.dropdown.Option("ipc")
        ])
        
        fecha_tf = ft.TextField(label="Fecha (Opcional)", hint_text="Formato DDMMAAAA", width=300, max_length=8)
        
        resultado_container = ft.Container(padding=10, border_radius=10, bgcolor=ft.colors.BLUE_50, visible=False)
        resultado_txt = ft.Text(size=20, weight="bold", color="blue")

        def consultar_click(e):
            if not drop.value: 
                self.mostrar_mensaje("Seleccione un indicador")
                return
            
            progress = ft.ProgressBar(width=200)
            self.page.add(progress)
            
            res = self.api.obtener_dato_api(self.db, self.usuario_conectado, drop.value, fecha_tf.value)
            
            self.page.controls.remove(progress) # Quitar barra de carga
            
            if res:
                resultado_txt.value = f"${res['valor']} {res['unidad']}"
                resultado_container.content = ft.Column([
                    ft.Text(f"Indicador: {drop.value.upper()}", size=12),
                    resultado_txt,
                    ft.Text(f"Fecha del valor: {res['fecha']}", italic=True)
                ], horizontal_alignment=ft.CrossAxisAlignment.CENTER)
                resultado_container.visible = True
            else:
                self.mostrar_mensaje("No se encontraron datos o error de conexión")
                resultado_container.visible = False
            self.page.update()

        self.page.add(
            ft.Column([
                ft.Text("Consulta Económica", size=24, weight="bold"),
                ft.Text("Deje la fecha vacía para el valor actual", size=12, color="grey"),
                drop, 
                fecha_tf,
                ft.ElevatedButton("Consultar", on_click=consultar_click, width=300, bgcolor="blue", color="white"),
                resultado_container,
                ft.TextButton("Volver al Menú", on_click=lambda _: self.mostrar_menu())
            ], horizontal_alignment=ft.CrossAxisAlignment.CENTER, spacing=15)
        )

    def mostrar_historial(self, e=None):
        self.limpiar_pantalla()
        
        logs = self.db.ejecutar("""
            SELECT indicator_name, indicator_value, value_date, query_date 
            FROM INDICATOR_LOG WHERE username_query = :u 
            ORDER BY query_date DESC FETCH FIRST 50 ROWS ONLY
        """, {"u": self.usuario_conectado}, True)
        
        lista_controles = []
        if logs:
            for l in logs:
                # l[0]=nombre, l[1]=valor, l[2]=fecha_valor, l[3]=fecha_query
                fecha_val = l[2].strftime('%d-%m-%Y') if l[2] else "N/A"
                fecha_qry = l[3].strftime('%d-%m %H:%M') if l[3] else "N/A"
                
                lista_controles.append(
                    ft.Container(
                        content=ft.Row([
                            ft.Icon(ft.icons.CHECK_CIRCLE, color="green"),
                            ft.Column([
                                ft.Text(f"{l[0].upper()}: ${l[1]}", weight="bold"),
                                ft.Text(f"Fecha Ind: {fecha_val}", size=12)
                            ], expand=True),
                            ft.Text(f"Audit: {fecha_qry}", size=10, color="grey")
                        ]),
                        padding=10,
                        border=ft.border.only(bottom=ft.border.BorderSide(1, "grey"))
                    )
                )
        else:
            lista_controles.append(ft.Text("No hay historial disponible."))

        self.page.add(
            ft.Column([
                ft.Text("Historial de Consultas", size=24, weight="bold"),
                ft.Container(
                    content=ft.ListView(controls=lista_controles, expand=True, spacing=5),
                    height=400,
                    border=ft.border.all(1, "grey"),
                    border_radius=5,
                    padding=5
                ),
                ft.ElevatedButton("Volver", on_click=lambda _: self.mostrar_menu(), width=300)
            ], horizontal_alignment=ft.CrossAxisAlignment.CENTER)
        )

def main(page: ft.Page):
    InterfazApp(page)

if __name__ == "__main__":
    ft.app(target=main)