import flet as ft
import oracledb
import os
import bcrypt
import requests
import datetime
from dotenv import load_dotenv

load_dotenv()

class BaseDatos:
    def __init__(self):
        self.usuario = os.getenv("ORACLE_USER")
        self.clave = os.getenv("ORACLE_PASSWORD")
        self.dsn = os.getenv("ORACLE_DSN")

    def obtener_conexion(self):
        try:
            return oracledb.connect(
                user=self.usuario,
                password=self.clave,
                dsn=self.dsn
            )
        except Exception as e:
            print("Error conexion BD:", e)
            return None

    def ejecutar(self, sql, params=None, select=False):
        try:
            with self.obtener_conexion() as conn:
                if not conn:
                    return None
                with conn.cursor() as cur:
                    cur.execute(sql, params or {})
                    if select:
                        return cur.fetchall()
                    conn.commit()
                    return True
        except Exception as e:
            print("SQL Error:", e)
            return None

    def crear_tablas(self):
        self.ejecutar("""
        CREATE TABLE USERS (
            id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
            username VARCHAR2(50) UNIQUE NOT NULL,
            password_hash VARCHAR2(100) NOT NULL
        )
        """)
        self.ejecutar("""
        CREATE TABLE INDICATOR_LOG (
            log_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
            indicator_name VARCHAR2(50),
            indicator_value NUMBER,
            value_date DATE,
            query_date DATE,
            username_query VARCHAR2(50),
            source_site VARCHAR2(100)
        )
        """)

class ServicioAPI:
    def __init__(self):
        self.url = "https://mindicador.cl/api"

    def obtener_dato_api(self, db, usuario, indicador, fecha):
        url = f"{self.url}/{indicador}"

        if fecha and fecha.isdigit() and len(fecha) == 8:
            f = f"{fecha[:2]}-{fecha[2:4]}-{fecha[4:]}"
            url = f"{url}/{f}"

        try:
            r = requests.get(url, timeout=10)
            if r.status_code != 200:
                return None

            data = r.json()
            if "serie" not in data or len(data["serie"]) == 0:
                return None

            item = data["serie"][0]
            valor = item["valor"]
            fecha_valor = datetime.datetime.strptime(
                item["fecha"][:10], "%Y-%m-%d"
            )

            db.ejecutar("""
            INSERT INTO INDICATOR_LOG
            (indicator_name, indicator_value, value_date, query_date, username_query, source_site)
            VALUES (:n,:v,:vd,:qd,:u,:s)
            """, {
                "n": data.get("nombre", indicador),
                "v": valor,
                "vd": fecha_valor,
                "qd": datetime.datetime.now(),
                "u": usuario,
                "s": "mindicador.cl"
            })

            return {
                "valor": valor,
                "fecha": fecha_valor.strftime("%d-%m-%Y")
            }

        except Exception as e:
            print("API Error:", e)
            return None

class InterfazApp:
    def __init__(self, page: ft.Page):
        self.page = page
        self.page.title = "Ecotech Finanzas"
        self.page.theme_mode = ft.ThemeMode.SYSTEM
        self.page.window.width = 390
        self.page.window.height = 680

        self.db = BaseDatos()
        self.api = ServicioAPI()
        self.usuario = None

        self.db.crear_tablas()

        self.snack = ft.SnackBar(ft.Text(""))
        self.page.snack_bar = self.snack

        self.root = ft.Container(
            content=ft.Column(
                horizontal_alignment=ft.CrossAxisAlignment.CENTER,
                spacing=16
            ),
            padding=24,
            width=360
        )

        self.page.add(self.root)
        self.mostrar_login()

    def limpiar(self):
        self.root.content.controls.clear()

    def mostrar_mensaje(self, texto, ok=False):
        self.snack.content.value = texto
        self.snack.bgcolor = "green" if ok else "red"
        self.snack.open = True
        self.page.update()

    def mostrar_login(self):
        self.limpiar()

        usuario_tf = ft.TextField(label="Usuario", width=300, autofocus=True)
        clave_tf = ft.TextField(label="Contrasena", password=True, width=300)

        def login(e):
            if not usuario_tf.value or not clave_tf.value:
                self.mostrar_mensaje("Debe completar usuario y contrasena")
                return

            datos = self.db.ejecutar(
                "SELECT password_hash FROM USERS WHERE username=:u",
                {"u": usuario_tf.value},
                True
            )

            if not datos or not bcrypt.checkpw(
                clave_tf.value.encode(),
                datos[0][0].encode()
            ):
                self.mostrar_mensaje("Usuario y o contrasena incorrectos")
                return

            self.usuario = usuario_tf.value
            self.mostrar_menu()

        self.root.content.controls.extend([
            ft.Text("Ecotech Finanzas", size=24, weight=ft.FontWeight.BOLD),
            usuario_tf,
            clave_tf,
            ft.ElevatedButton("Ingresar", on_click=login, width=300),
            ft.TextButton("Crear cuenta", on_click=self.mostrar_registro)
        ])

        self.page.update()

    def mostrar_registro(self, e=None):
        self.limpiar()

        usuario_tf = ft.TextField(label="Usuario", width=300)
        clave_tf = ft.TextField(label="Contrasena", password=True, width=300)

        def registrar(e):
            if not usuario_tf.value or not clave_tf.value:
                self.mostrar_mensaje("Debe completar todos los campos")
                return

            if len(clave_tf.value) < 6:
                self.mostrar_mensaje("La contrasena debe tener al menos 6 caracteres")
                return

            hash_pw = bcrypt.hashpw(
                clave_tf.value.encode(),
                bcrypt.gensalt()
            ).decode()

            ok = self.db.ejecutar(
                "INSERT INTO USERS(username,password_hash) VALUES(:u,:p)",
                {"u": usuario_tf.value, "p": hash_pw}
            )

            if ok:
                self.mostrar_login()
            else:
                self.mostrar_mensaje("El usuario ya existe")

        self.root.content.controls.extend([
            ft.Text("Registro", size=22, weight=ft.FontWeight.BOLD),
            usuario_tf,
            clave_tf,
            ft.ElevatedButton("Registrar", on_click=registrar, width=300),
            ft.TextButton("Volver", on_click=self.mostrar_login)
        ])

        self.page.update()

    def mostrar_menu(self):
        self.limpiar()

        self.root.content.controls.extend([
            ft.Text(f"Usuario: {self.usuario}", weight=ft.FontWeight.BOLD),
            ft.ElevatedButton("Consultar indicador", width=300, on_click=self.mostrar_consulta),
            ft.ElevatedButton("Historial", width=300, on_click=self.mostrar_historial),
            ft.TextButton("Cerrar sesion", on_click=self.mostrar_login)
        ])

        self.page.update()

    def mostrar_consulta(self, e=None):
        self.limpiar()

        indicador_dd = ft.Dropdown(
            width=300,
            options=[
                ft.dropdown.Option("uf"),
                ft.dropdown.Option("dolar"),
                ft.dropdown.Option("euro"),
                ft.dropdown.Option("utm"),
                ft.dropdown.Option("ipc")
            ]
        )

        fecha_tf = ft.TextField(label="Fecha DDMMAAAA", width=300)
        resultado_txt = ft.Text(size=20, weight=ft.FontWeight.BOLD)

        def consultar(e):
            if not indicador_dd.value:
                self.mostrar_mensaje("Debe seleccionar un indicador")
                return

            res = self.api.obtener_dato_api(
                self.db,
                self.usuario,
                indicador_dd.value,
                fecha_tf.value
            )

            if res:
                resultado_txt.value = f"${res['valor']} {res['fecha']}"
            else:
                resultado_txt.value = ""
                self.mostrar_mensaje("Sin datos")

            self.page.update()

        self.root.content.controls.extend([
            ft.Text("Consulta", size=22, weight=ft.FontWeight.BOLD),
            indicador_dd,
            fecha_tf,
            ft.ElevatedButton("Consultar", on_click=consultar, width=300),
            resultado_txt,
            ft.TextButton("Volver", on_click=self.mostrar_menu)
        ])

        self.page.update()

    def mostrar_historial(self, e=None):
        self.limpiar()

        data = self.db.ejecutar("""
        SELECT indicator_name, indicator_value, value_date
        FROM INDICATOR_LOG
        WHERE username_query=:u
        ORDER BY query_date DESC FETCH FIRST 20 ROWS ONLY
        """, {"u": self.usuario}, True)

        lista = ft.ListView(height=360, width=330)

        if data:
            for d in data:
                lista.controls.append(
                    ft.ListTile(
                        title=ft.Text(f"{d[0]} ${d[1]}", weight=ft.FontWeight.BOLD),
                        subtitle=ft.Text(d[2].strftime("%d-%m-%Y"))
                    )
                )
        else:
            lista.controls.append(ft.Text("Sin historial"))

        self.root.content.controls.extend([
            ft.Text("Historial", size=22, weight=ft.FontWeight.BOLD),
            lista,
            ft.TextButton("Volver", on_click=self.mostrar_menu)
        ])

        self.page.update()

def main(page: ft.Page):
    InterfazApp(page)

if __name__ == "__main__":
    ft.run(main)
